var possible_graphs = [
{"nodes": ["S","A","B","C","D","E","G"],
"heuristic": {"S":18,"A":16,"B":8,"C":8,"G":0,"D":7,"E":7},
"edges":["SA","AB","BC","CG","BD","DC","DE","SB"],
"costs": [2,6,8,7,2,1,5,8],
"alg" : []
},
{"nodes": ["S","B","C","D","E","F","H", "G"],
"heuristic": {"S":18,"A":16,"B":8,"C":8,"G":0,"D":7,"E":7},
"edges":["SB","SE","SF", "BF","BG", "BC", "CG", "CD", "DG", "DH","EF","GF", "GH"],
"costs": [1,4,8,6,6,2,2,1,1,4,5,1,1],
"alg" : []
},
{"nodes": ["S","A","C","E","B","D","F","G"],
"heuristic": {"S":11,"A":10,"C":5,"E":3,"G":0,"B":4,"D":5,"F":4},
"edges":["SA","AC","CE","EG","CG","SB","BC","BD","DF"],
"costs": [6,5,1,3,4,5,2,3,4],
"alg" : []
},
{"nodes": ["S","A","C","D","B","G"],
"heuristic": {"S":5,"A":5,"C":2,"D":3,"G":0,"B":5},
"edges":["SA","AC","CD","DG","CG","AG","SB","BC"],
"costs": [3,1,1,2,7,8,2,4],
"alg" : []
},
{"nodes": ["S","A","C","E","B","D","G"],
"heuristic": {"S":8,"A":8,"C":6,"E":6,"G":0,"B":7,"D":0},
"edges":["SA","AC","CE","EG","CG","SB","BC","BD","DG"],
"costs": [1,4,7,8,5,1,1,8,1],
"alg" : []
},
{"nodes": ["S","A","B","D","C","G"],
"heuristic": {"S":15,"A":11,"B":5,"D":3,"G":0,"C":2},
"edges":["SA","AB","BD","DG","BG","AC","CG","AD"],
"costs": [6,7,5,3,7,8,4,8],
"alg" : []
},
{"nodes": ["S","A","B","C","E","D","G"],
"heuristic": {"S":16,"A":10,"B":7,"C":3,"E":1,"G":0,"D":8},
"edges":["SA","AB","BC","CE","CG","BD","DC","AC","SB"],
"costs": [7,1,8,2,5,2,2,4,6],
"alg" : []
},
{"nodes": ["S","A","C","D","B","G"],
"heuristic": {"S":9,"A":6,"C":4,"D":1,"G":0,"B":7},
"edges":["SA","AC","CD","DG","CG","AD","SB","BC"],
"costs": [5,5,2,2,8,4,4,2],
"alg" : []
},
{"nodes": ["S","A","B","C","G"],
"heuristic": {"S":6,"A":6,"B":2,"C":1,"G":0},
"edges":["SA","AB","BC","CG","BG","AG","SB"],
"costs": [5,6,2,2,6,5,3],
"alg" : []
},
{"nodes": ["S","A","C","E","B","D","G"],
"heuristic": {"S":8,"A":7,"C":3,"E":0,"B":4,"D":0,"G":0},
"edges":["SA","AC","CE","EB","BD","DG","EG","CG","SB"],
"costs": [1,2,4,6,3,1,1,5,5],
"alg" : []
},
{"nodes": ["S","A","C","F","E","D","B","G"],
"heuristic": {"S":15,"A":8,"C":5,"F":1,"E":7,"G":0,"D":9,"B":9},
"edges":["SA","AC","CF","FE","EG","FG","AD","SB","BE","BF"],
"costs": [6,4,4,3,8,1,4,5,2,8],
"alg" : []
},
{"nodes": ["S","A","B","C","G"],
"heuristic": {"S":14,"A":4,"B":3,"C":0,"G":0},
"edges":["SA","AB","BC","CG","BG","AC","AG"],
"costs": [8,1,8,1,4,6,5],
"alg" : []
},
{"nodes": ["S","A","C","D","B","G"],
"heuristic": {"S":5,"A":6,"C":2,"D":6,"G":0,"B":6},
"edges":["SA","AC","CD","DG","CG","SB","BC","BD"],
"costs": [5,3,1,5,2,1,7,1],
"alg" : []
},
{"nodes": ["S","A","C","E","B","D","G"],
"heuristic": {"S":11,"A":12,"C":6,"E":0,"G":0,"B":5,"D":2},
"edges":["SA","AC","CE","EG","CG","SB","BD","DG","BE"],
"costs": [3,6,4,2,7,4,3,3,6],
"alg" : []
},
{"nodes": ["S","A","C","E","B","D","F","G"],
"heuristic": {"S":11,"A":10,"C":4,"E":6,"G":0,"B":7,"D":7,"F":4},
"edges":["SA","AC","CE","EG","CG","SB","BC","BD","DC","DF"],
"costs": [8,6,1,6,3,1,7,2,4,1],
"alg" : []
},
{"nodes": ["S","A","B","D","E","C","F","G"],
"heuristic": {"S":8,"A":4,"B":3,"D":3,"E":1,"G":0,"C":8,"F":8},
"edges":["SA","AB","BD","DE","EG","BE","AC","CF","CG","AD"],
"costs": [3,1,6,3,1,4,6,2,7,1],
"alg" : []
},
{"nodes": ["S","A","C","B","E","D","F","G"],
"heuristic": {"S":14,"A":10,"C":12,"B":7,"E":2,"D":1,"F":8,"G":0},
"edges":["SA","AC","CB","BE","ED","DF","DG","EG","AD","SB"],
"costs": [6,5,2,6,1,4,2,7,7,6],
"alg" : []
},
{"nodes": ["S","A","B","C","D","G"],
"heuristic": {"S":9,"A":11,"B":9,"C":1,"D":3,"G":0},
"edges":["SA","AB","BC","CD","DG","CG","AC","SB"],
"costs": [1,2,5,4,3,3,7,5],
"alg" : []
},
{"nodes": ["S","A","C","E","D","B","G"],
"heuristic": {"S":8,"A":1,"C":0,"E":5,"G":0,"D":0,"B":5},
"edges":["SA","AC","CE","CG","AD","DC","DG","SB","BG"],
"costs": [5,2,8,1,1,5,1,5,6],
"alg" : []
},
{"nodes": ["S","A","C","B","D","G"],
"heuristic": {"S":6,"A":4,"C":3,"B":3,"D":1,"G":0},
"edges":["SA","AC","CB","BD","DG","CD","CG","SB"],
"costs": [1,1,7,4,1,3,5,6],
"alg" : []
},
{"nodes": ["S","A","C","D","B","G"],
"heuristic": {"S":14,"A":8,"C":3,"D":5,"G":0,"B":8},
"edges":["SA","AC","CD","DG","CG","SB","BC","BD"],
"costs": [8,5,3,5,4,8,6,2],
"alg" : []
},
{"nodes": ["S","A","C","D","E","B","G"],
"heuristic": {"S":5,"A":6,"C":5,"D":3,"G":0,"E":2,"B":6},
"edges":["SA","AC","CD","DG","CE","AD","AG","SB","BG"],
"costs": [1,6,2,2,7,4,7,2,6],
"alg" : []
},
{"nodes": ["S","A","C","D","B","E","G"],
"heuristic": {"S":16,"A":11,"C":5,"D":3,"G":0,"B":14,"E":9},
"edges":["SA","AC","CD","DG","CG","AD","SB","BE","EC"],
"costs": [8,5,5,4,6,7,4,5,3],
"alg" : []
},
{"nodes": ["S","A","C","D","B","G"],
"heuristic": {"S":10,"A":10,"C":5,"D":2,"G":0,"B":9},
"edges":["SA","AC","CD","DG","CG","AD","SB","BC"],
"costs": [6,6,3,3,8,7,3,3],
"alg" : []
},
{"nodes": ["S","A","B","C","G"],
"heuristic": {"S":4,"A":2,"B":6,"C":3,"G":0},
"edges":["SA","AB","BC","CG","AC","AG","SG"],
"costs": [2,1,3,2,2,5,8],
"alg" : []
},
{"nodes": ["S","A","B","C","G"],
"heuristic": {"S":14,"A":7,"B":6,"C":0,"G":0},
"edges":["SA","AB","BC","CG","BG","AC","AG"],
"costs": [7,1,8,1,6,8,7],
"alg" : []
},
{"nodes": ["S","A","B","C","D","E","F","G"],
"heuristic": {"S":11,"A":12,"B":9,"C":2,"G":0,"D":7,"E":0,"F":5},
"edges":["SA","AB","BC","CG","BD","DC","BE","EF","AC","SB"],
"costs": [7,7,7,4,3,4,7,2,8,2],
"alg" : []
},
{"nodes": ["S","A","C","D","B","G"],
"heuristic": {"S":7,"A":6,"C":5,"D":5,"G":0,"B":6},
"edges":["SA","AC","CD","DG","CG","SB","BC","BD"],
"costs": [5,2,3,5,6,2,7,1],
"alg" : []
},
{"nodes": ["S","A","C","D","B","G"],
"heuristic": {"S":6,"A":5,"C":4,"D":9,"B":5,"G":0},
"edges":["SA","AC","CD","DB","BG","CG","AG","SB"],
"costs": [1,2,4,2,6,4,7,2],
"alg" : []
},
{"nodes": ["S","A","C","E","F","B","D","G"],
"heuristic": {"S":5,"A":9,"C":2,"E":8,"F":3,"G":0,"B":5,"D":3},
"edges":["SA","AC","CE","CF","FG","CG","SB","BC","BD","DF"],
"costs": [6,5,4,7,2,3,2,7,2,1],
"alg" : []
},
{"nodes": ["S","A","B","C","E","D","F","G"],
"heuristic": {"S":15,"A":11,"B":9,"C":2,"E":9,"G":0,"D":0,"F":0},
"edges":["SA","AB","BC","CE","CG","BD","DF","DG","SB"],
"costs": [4,1,7,3,3,8,8,1,7],
"alg" : []
},
{"nodes": ["S","A","B","C","D","G"],
"heuristic": {"S":9,"A":3,"B":2,"C":2,"G":0,"D":0},
"edges":["SA","AB","BC","CG","GD","BG","AG","SB"],
"costs": [5,1,7,1,2,4,6,8],
"alg" : []
},
{"nodes": ["S","A","C","E","F","B","D","G"],
"heuristic": {"S":12,"A":11,"C":6,"E":10,"F":4,"B":9,"D":4,"G":0},
"edges":["SA","AC","CE","CF","FB","BD","DG","FD","AD","SB"],
"costs": [3,5,1,1,8,7,4,1,8,5],
"alg" : []
},
{"nodes": ["S","A","C","E","D","F","B","G"],
"heuristic": {"S":7,"A":5,"C":7,"E":4,"D":3,"F":7,"B":2,"G":0},
"edges":["SA","AC","CE","AD","DF","FB","BG","DG","AG","SB"],
"costs": [2,4,1,4,6,3,4,2,7,4],
"alg" : []
},
{"nodes": ["S","A","B","C","G"],
"heuristic": {"S":9,"A":3,"B":1,"C":0,"G":0},
"edges":["SA","AB","BC","CG","BG","AC","AG"],
"costs": [5,2,6,1,1,5,6],
"alg" : []
},
{"nodes": ["S","A","C","D","E","B","G"],
"heuristic": {"S":6,"A":6,"C":4,"D":0,"E":1,"G":0,"B":3},
"edges":["SA","AC","CD","DE","EG","DG","AD","SB","BD"],
"costs": [1,2,2,3,2,1,4,3,3],
"alg" : []
},
{"nodes": ["S","A","B","C","G"],
"heuristic": {"S":8,"A":5,"B":3,"C":4,"G":0},
"edges":["SA","AB","BC","CG","BG","AG","SB"],
"costs": [3,3,1,3,5,5,4],
"alg" : []
},
{"nodes": ["S","A","B","C","G"],
"heuristic": {"S":8,"A":6,"B":0,"C":2,"G":0},
"edges":["SA","AB","BC","CG","BG","AC","AG"],
"costs": [4,7,4,4,2,1,5],
"alg" : []
},
{"nodes": ["S","A","B","D","C","G"],
"heuristic": {"S":18,"A":11,"B":7,"D":3,"G":0,"C":10},
"edges":["SA","AB","BD","DG","BG","AC","CD","AD"],
"costs": [7,5,3,4,6,2,5,8],
"alg" : []
},
{"nodes": ["S","A","C","D","B","G"],
"heuristic": {"S":8,"A":4,"C":1,"D":5,"G":0,"B":5},
"edges":["SA","AC","CD","DG","CG","SB","BC","BG"],
"costs": [7,4,5,5,2,4,2,7],
"alg" : []
},
{"nodes": ["S","A","C","D","F","B","E","G"],
"heuristic": {"S":7,"A":3,"C":9,"D":3,"G":0,"F":2,"B":3,"E":0},
"edges":["SA","AC","CD","DG","CF","AD","SB","BE","EG","BG"],
"costs": [3,2,7,3,6,1,5,3,2,7],
"alg" : []
},
{"nodes": ["S","A","B","C","D","G"],
"heuristic": {"S":15,"A":6,"B":9,"C":3,"D":0,"G":0},
"edges":["SA","AB","BC","CD","DG","CG","BG","AC"],
"costs": [8,5,3,4,2,5,8,1],
"alg" : []
},
{"nodes": ["S","A","B","C","G"],
"heuristic": {"S":5,"A":6,"B":4,"C":8,"G":0},
"edges":["SA","AB","BC","CG","BG","AG","SB"],
"costs": [1,1,8,7,5,7,5],
"alg" : []
},
{"nodes": ["S","A","B","D","C","G"],
"heuristic": {"S":10,"A":8,"B":7,"D":3,"G":0,"C":5},
"edges":["SA","AB","BD","DG","BG","AC","CD","AD"],
"costs": [1,7,4,2,6,2,4,8],
"alg" : []
},
{"nodes": ["S","A","C","D","B","G"],
"heuristic": {"S":12,"A":9,"C":2,"D":1,"G":0,"B":5},
"edges":["SA","AC","CD","DG","CG","SB","BC","BD"],
"costs": [8,8,4,1,1,4,6,8],
"alg" : []
},
{"nodes": ["S","A","C","B","G"],
"heuristic": {"S":13,"A":9,"C":1,"B":7,"G":0},
"edges":["SA","AC","CB","BG","CG","AG","SB"],
"costs": [6,7,3,7,1,8,7],
"alg" : []
},
{"nodes": ["S","A","C","F","D","E","B","G"],
"heuristic": {"S":8,"A":4,"C":12,"F":6,"D":2,"G":0,"E":1,"B":6},
"edges":["SA","AC","CF","FD","DG","AD","AE","EG","SB","BE"],
"costs": [6,6,5,5,2,2,1,2,1,4],
"alg" : []
}
]
